export function FormatMiaoMsg(msg) {
  return {
    post_type: msg.post_type,
    message_id: msg.message_id,
    nt: msg.nt,
    user_id: msg.user_id,
    user_uid: msg.user_uid,
    time: msg.time,
    seq: msg.seq,
    msg_id: msg.msg_id,
    rand: msg.rand,
    font: msg.font,
    message: msg.message,
    raw_message: msg.raw_message,
    message_type: msg.message_type,
    sender: {
      user_id: msg.sender.user_id,
      user_uid: msg.sender.user_uid,
      nickname: msg.sender.nickname,
      sub_id: msg.sender.sub_id,
      card: msg.sender.card,
      sex: msg.sender.sex,
      age: msg.sender.age,
      area: msg.sender.area,
      level: msg.sender.level,
      role: msg.sender.role,
      title: msg.sender.title,
    },
    group_id: msg.group_id,
    group_name: msg.group_name,
    block: msg.block,
    sub_type: msg.sub_type,
    anonymous: msg.anonymous,
    atme: msg.atme,
    atall: msg.atall,
    source: msg.source,
  }
}
